services:
  tornet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tornet
    ports:
      - "19050:19050"
    restart: unless-stopped
    volumes:
      - tor-data:/var/lib/tor
    working_dir: /app
    command: ["python3", "tornet/tornet.py", "--interval", "60", "--count", "0", "--prefer-ru", "--fallback-exits", "any"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  tor-data:
